apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "webui.name" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  {{- $versionLabel := dict "app.kubernetes.io/version" ( include "common.images.version" ( dict "imageRoot" .Values.webui.image "chart" .Chart ) ) }}
  {{- $labels := include "common.tplvalues.merge" ( dict "values" ( list .Values.commonLabels $versionLabel ) "context" . ) }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: webui
  {{- if or .Values.webui.deploymentAnnotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.webui.deploymentAnnotations .Values.commonAnnotations) "context" .) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.webui.autoscaling.enabled }}
  replicas: {{ .Values.webui.replicaCount }}
  {{- end }}
  {{- if .Values.webui.updateStrategy }}
  strategy: {{- toYaml .Values.webui.updateStrategy | nindent 4 }}
  {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" (dict "values" (list .Values.webui.podLabels .Values.commonLabels) "context" .) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
      app.kubernetes.io/component: webui
  template:
    metadata:
      annotations:
        {{- if .Values.webui.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.webui.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
        {{- if .Values.commonAnnotations }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
        {{- end }}
      labels: {{- include "common.labels.standard" ( dict "customLabels" $podLabels "context" $ ) | nindent 8 }}
        app.kubernetes.io/component: webui
    spec:
      serviceAccountName: {{ template "webui.serviceAccountName" . }}
      {{- include "webui.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.webui.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.webui.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.webui.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.webui.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.webui.podAffinityPreset "component" "webui" "customLabels" $podLabels "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.webui.podAntiAffinityPreset "component" "webui" "customLabels" $podLabels "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.webui.nodeAffinityPreset.type "key" .Values.webui.nodeAffinityPreset.key "values" .Values.webui.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.webui.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.webui.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.webui.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.webui.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.webui.priorityClassName }}
      priorityClassName: {{ .Values.webui.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.webui.schedulerName }}
      schedulerName: {{ .Values.webui.schedulerName | quote }}
      {{- end }}
      {{- if .Values.webui.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.webui.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.webui.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.webui.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.webui.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.webui.terminationGracePeriodSeconds }}
      {{- end }}
      initContainers:
        {{- if .Values.webui.initContainers }}
          {{- include "common.tplvalues.render" (dict "value" .Values.webui.initContainers "context" $) | nindent 8 }}
        {{- end }}
      containers:
        - name: webui
          image: {{ template "webui.image" . }}
          imagePullPolicy: {{ .Values.webui.image.pullPolicy }}
          {{- if .Values.webui.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.webui.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.webui.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.webui.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.webui.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.webui.args "context" $) | nindent 12 }}
          {{- end }}
          env:
            - name: OLLAMA_API_BASE_URL
              value:  "http://{{ include "ollama.name" . }}:{{ .Values.ollama.service.ports.http }}/api" 
            {{- if .Values.webui.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.webui.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.webui.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.webui.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.webui.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.webui.extraEnvVarsSecret "context" $) }}
            {{- end }}
          {{- if .Values.webui.resources }}
          resources: {{- toYaml .Values.webui.resources | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.webui.containerPorts.http }}
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.webui.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.webui.customLivenessProbe "context" $) | nindent 12 }}
          {{- else if .Values.webui.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.webui.livenessProbe "enabled") "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.webui.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.webui.customReadinessProbe "context" $) | nindent 12 }}
          {{- else if .Values.webui.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.webui.readinessProbe "enabled") "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.webui.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.webui.customStartupProbe "context" $) | nindent 12 }}
          {{- else if .Values.webui.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.webui.startupProbe "enabled") "context" $) | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.webui.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.webui.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: webui-data
              mountPath: {{ .Values.webui.persistence.mountPath }}
              {{- if .Values.webui.persistence.subPath }}
              subPath: {{ .Values.webui.persistence.subPath }}
              {{- end }}
          {{- if .Values.webui.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.webui.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        {{- if .Values.webui.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.webui.sidecars "context" $) | nindent 8 }}
        {{- end }}
      volumes:
        - name: webui-data
        {{- if .Values.webui.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ default (include "webui.name" .) .Values.webui.persistence.existingClaim }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        {{- if .Values.webui.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.webui.extraVolumes "context" $) | nindent 8 }}
        {{- end }}