{{- if .Values.webui.autoscaling.enabled }}
apiVersion: {{ include "common.capabilities.hpa.apiVersion" (dict "context" $) }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "webui.name" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: webui
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
    kind: Deployment
    name: {{ include "webui.name" . }}
  minReplicas: {{ .Values.webui.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.webui.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.webui.autoscaling.targetMemory }}
    - type: Resource
      resource:
        name: memory
        {{- if semverCompare "<1.23-0" (include "common.capabilities.kubeVersion" .) }}
        targetAverageUtilization: {{ .Values.webui.autoscaling.targetMemory  }}
        {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.webui.autoscaling.targetMemory }}
        {{- end }}
    {{- end }}
    {{- if .Values.webui.autoscaling.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        {{- if semverCompare "<1.23-0" (include "common.capabilities.kubeVersion" .) }}
        targetAverageUtilization: {{ .Values.webui.autoscaling.targetCPU }}
        {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.webui.autoscaling.targetCPU }}
        {{- end }}
    {{- end }}
{{- end }}