annotations:
  licenses: MIT
apiVersion: v2
appVersion: 0.1.102
version: 0.1.4
name: ollama-webui
description: "Chart to deploy Open WebUI, a ChatGPT-Style Web UI Client for Ollama 🦙"
home: https://github.com/braveokafor/ollama-webui-helm/
icon: https://ollama.ai/public/ollama.png
maintainers:
  - email: okaforbrave@gmail.com
    name: braveokafor
    url: https://www.linkedin.com/in/braveokafor/
sources:
  - https://github.com/jmorganca/ollama/
  - https://github.com/open-webui/open-webui/
  - https://github.com/braveokafor/ollama-webui-helm/
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
keywords:
  - ollama
  - open-webui
  - llm
  - llama
