annotations:
  licenses: MIT
apiVersion: v2
appVersion: 0.1.17
version: 0.1.3
name: ollama-webui
description: "ChatGPT-Style Web UI Client for Ollama 🦙"
home: https://github.com/braveokafor/ollama-webui-helm/
icon: https://ollama.ai/public/ollama.png
maintainers:
  - email: okaforbrave@gmail.com
    name: braveokafor
    url: https://www.linkedin.com/in/braveokafor/
sources:
  - https://github.com/jmorganca/ollama
  - https://github.com/ollama-webui/ollama-webui
  - https://github.com/braveokafor/ollama-webui-helm/
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
keywords:
  - ollama
  - ollama-webui
  - llm
  - llama
