{{- if and (or .Values.mongodb.enabled .Values.externalDatabase.enabled) (not .Values.externalDatabase.existingSecret)}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-mongodb" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data: 
  {{- if .Values.mongodb.enabled }}
  mongodb-database-url: {{ default (printf "mongodb://%s:%s@%s-mongodb.%s:27017/" .Values.mongodb.auth.rootUser .Values.mongodb.auth.rootPassword .Release.Name .Release.Namespace) .Values.mongodb.databaseUrl | b64enc | quote }}
  {{- else }}
  mongodb-database-url: {{ .Values.externalDatabase.databaseUrl | b64enc | quote }}
  {{- end }} 
{{- end }}