{{- if and .Values.ollama.persistence.enabled (not .Values.ollama.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "common.names.fullname" . }}-ollama
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.ollama.persistence.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.ollama.persistence.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.ollama.persistence.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.ollama.persistence.accessModes }}
    - {{ . | quote }}
      {{- end }}
  resources:
    requests:
      storage: {{ .Values.ollama.persistence.size | quote }}
  {{- include "common.storage.class" (dict "persistence" .Values.ollama.persistence "global" .Values.global) | nindent 2 }}
  {{- if .Values.ollama.persistence.dataSource }}
  dataSource: {{- include "common.tplvalues.render" (dict "value" .Values.ollama.persistence.dataSource "context" $) | nindent 4 }}
  {{- end }}
  {{- if .Values.ollama.persistence.selector }}
  selector: {{- include "common.tplvalues.render" (dict "value" .Values.ollama.persistence.selector "context" $) | nindent 4 }}
  {{- end -}}
{{- end }}