apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-webui
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.webui.service.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.webui.service.annotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.webui.service.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.webui.service.type }}
  {{- if and .Values.webui.service.clusterIP (eq .Values.webui.service.type "ClusterIP") }}
  clusterIP: {{ .Values.webui.service.clusterIP }}
  {{- end }}
  {{- if or (eq .Values.webui.service.type "LoadBalancer") (eq .Values.webui.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.webui.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.webui.service.type "LoadBalancer") (not (empty .Values.webui.service.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{ .Values.webui.service.loadBalancerSourceRanges }}
  {{- end }}
  {{- if and (eq .Values.webui.service.type "LoadBalancer") (not (empty .Values.webui.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.webui.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.webui.service.sessionAffinity }}
  sessionAffinity: {{ .Values.webui.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.webui.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.webui.service.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.webui.service.ports.http }}
      protocol: TCP
      targetPort: http
      {{- if (and (or (eq .Values.webui.service.type "NodePort") (eq .Values.webui.service.type "LoadBalancer")) (not (empty .Values.webui.service.nodePorts.http))) }}
      nodePort: {{ .Values.webui.service.nodePorts.http }}
      {{- else if eq .Values.webui.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- if .Values.webui.service.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.webui.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  selector: {{- include "webui.selectorLabels" . | nindent 4 }}